#!/bin/bash
# This script Interactively list users and their public keys that the SSH server
# accepts for Public Key Authentication. It then allows you to delete a specific
# public key.

USERNAME=""
# If username is passed as argument, check if it exists and proceed
id "$1" &> /dev/null
if [[ $? == 0 ]]; then
    USERNAME=$1
  else
    echo "Choose the username whose public key that you want to delete."
fi
